/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as TabusRouteImport } from './routes/tabus'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as NewsletterBestaetigenRouteImport } from './routes/newsletter-bestaetigen'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FotoshootingRouteImport } from './routes/fotoshooting'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ErfahrungsberichteRouteImport } from './routes/erfahrungsberichte'
import { Route as DuoSessionsRouteImport } from './routes/duo-sessions'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ContentDrehRouteImport } from './routes/content-dreh'
import { Route as BuchungRouteImport } from './routes/buchung'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAdminUmplanenRouteImport } from './routes/_authenticated/admin.umplanen'
import { Route as AuthenticatedAdminTerminplanRouteImport } from './routes/_authenticated/admin.terminplan'
import { Route as AuthenticatedAdminTermineRouteImport } from './routes/_authenticated/admin.termine'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin.newsletter'
import { Route as AuthenticatedAdminKundenRouteImport } from './routes/_authenticated/admin.kunden'
import { Route as AuthenticatedAdminKassenbuchRouteImport } from './routes/_authenticated/admin.kassenbuch'
import { Route as AuthenticatedAdminKalenderRouteImport } from './routes/_authenticated/admin.kalender'
import { Route as AuthenticatedAdminFotoshootingRouteImport } from './routes/_authenticated/admin.fotoshooting'
import { Route as AuthenticatedAdminErfahrungsberichteRouteImport } from './routes/_authenticated/admin.erfahrungsberichte'
import { Route as AuthenticatedAdminDuoRouteImport } from './routes/_authenticated/admin.duo'
import { Route as AuthenticatedAdminCustomRouteImport } from './routes/_authenticated/admin.custom'
import { Route as AuthenticatedAdminContentdrehRouteImport } from './routes/_authenticated/admin.contentdreh'
import { Route as AuthenticatedAdminAgbRouteImport } from './routes/_authenticated/admin.agb'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksPaymentRemindersRouteImport } from './routes/api/public/hooks/payment-reminders'
import { Route as ApiPublicCalendarSplatRouteImport } from './routes/api/public/calendar.$'
import { Route as AuthenticatedAdminEmailVorschauLogIdRouteImport } from './routes/_authenticated/admin.email-vorschau.$logId'
import { Route as AuthenticatedAdminBuchungIdRouteImport } from './routes/_authenticated/admin.buchung.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const TabusRoute = TabusRouteImport.update({
  id: '/tabus',
  path: '/tabus',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterBestaetigenRoute = NewsletterBestaetigenRouteImport.update({
  id: '/newsletter-bestaetigen',
  path: '/newsletter-bestaetigen',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoshootingRoute = FotoshootingRouteImport.update({
  id: '/fotoshooting',
  path: '/fotoshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfahrungsberichteRoute = ErfahrungsberichteRouteImport.update({
  id: '/erfahrungsberichte',
  path: '/erfahrungsberichte',
  getParentRoute: () => rootRouteImport,
} as any)
const DuoSessionsRoute = DuoSessionsRouteImport.update({
  id: '/duo-sessions',
  path: '/duo-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentDrehRoute = ContentDrehRouteImport.update({
  id: '/content-dreh',
  path: '/content-dreh',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchungRoute = BuchungRouteImport.update({
  id: '/buchung',
  path: '/buchung',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUmplanenRoute =
  AuthenticatedAdminUmplanenRouteImport.update({
    id: '/umplanen',
    path: '/umplanen',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTerminplanRoute =
  AuthenticatedAdminTerminplanRouteImport.update({
    id: '/terminplan',
    path: '/terminplan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTermineRoute =
  AuthenticatedAdminTermineRouteImport.update({
    id: '/termine',
    path: '/termine',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKundenRoute =
  AuthenticatedAdminKundenRouteImport.update({
    id: '/kunden',
    path: '/kunden',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKassenbuchRoute =
  AuthenticatedAdminKassenbuchRouteImport.update({
    id: '/kassenbuch',
    path: '/kassenbuch',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKalenderRoute =
  AuthenticatedAdminKalenderRouteImport.update({
    id: '/kalender',
    path: '/kalender',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFotoshootingRoute =
  AuthenticatedAdminFotoshootingRouteImport.update({
    id: '/fotoshooting',
    path: '/fotoshooting',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminErfahrungsberichteRoute =
  AuthenticatedAdminErfahrungsberichteRouteImport.update({
    id: '/erfahrungsberichte',
    path: '/erfahrungsberichte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDuoRoute = AuthenticatedAdminDuoRouteImport.update({
  id: '/duo',
  path: '/duo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCustomRoute =
  AuthenticatedAdminCustomRouteImport.update({
    id: '/custom',
    path: '/custom',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentdrehRoute =
  AuthenticatedAdminContentdrehRouteImport.update({
    id: '/contentdreh',
    path: '/contentdreh',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgbRoute = AuthenticatedAdminAgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaymentRemindersRoute =
  ApiPublicHooksPaymentRemindersRouteImport.update({
    id: '/api/public/hooks/payment-reminders',
    path: '/api/public/hooks/payment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarSplatRoute = ApiPublicCalendarSplatRouteImport.update({
  id: '/api/public/calendar/$',
  path: '/api/public/calendar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminEmailVorschauLogIdRoute =
  AuthenticatedAdminEmailVorschauLogIdRouteImport.update({
    id: '/email-vorschau/$logId',
    path: '/email-vorschau/$logId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBuchungIdRoute =
  AuthenticatedAdminBuchungIdRouteImport.update({
    id: '/buchung/$id',
    path: '/buchung/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/buchung': typeof BuchungRoute
  '/content-dreh': typeof ContentDrehRoute
  '/custom': typeof CustomRoute
  '/datenschutz': typeof DatenschutzRoute
  '/duo-sessions': typeof DuoSessionsRoute
  '/erfahrungsberichte': typeof ErfahrungsberichteRoute
  '/faq': typeof FaqRoute
  '/fotoshooting': typeof FotoshootingRoute
  '/impressum': typeof ImpressumRoute
  '/kalender': typeof KalenderRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/mcp': typeof McpRoute
  '/newsletter-bestaetigen': typeof NewsletterBestaetigenRoute
  '/online': typeof OnlineRoute
  '/preise': typeof PreiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabus': typeof TabusRoute
  '/ueber-mich': typeof UeberMichRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/agb': typeof AuthenticatedAdminAgbRoute
  '/admin/contentdreh': typeof AuthenticatedAdminContentdrehRoute
  '/admin/custom': typeof AuthenticatedAdminCustomRoute
  '/admin/duo': typeof AuthenticatedAdminDuoRoute
  '/admin/erfahrungsberichte': typeof AuthenticatedAdminErfahrungsberichteRoute
  '/admin/fotoshooting': typeof AuthenticatedAdminFotoshootingRoute
  '/admin/kalender': typeof AuthenticatedAdminKalenderRoute
  '/admin/kassenbuch': typeof AuthenticatedAdminKassenbuchRoute
  '/admin/kunden': typeof AuthenticatedAdminKundenRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/termine': typeof AuthenticatedAdminTermineRoute
  '/admin/terminplan': typeof AuthenticatedAdminTerminplanRoute
  '/admin/umplanen': typeof AuthenticatedAdminUmplanenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/buchung/$id': typeof AuthenticatedAdminBuchungIdRoute
  '/admin/email-vorschau/$logId': typeof AuthenticatedAdminEmailVorschauLogIdRoute
  '/api/public/calendar/$': typeof ApiPublicCalendarSplatRoute
  '/api/public/hooks/payment-reminders': typeof ApiPublicHooksPaymentRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/buchung': typeof BuchungRoute
  '/content-dreh': typeof ContentDrehRoute
  '/custom': typeof CustomRoute
  '/datenschutz': typeof DatenschutzRoute
  '/duo-sessions': typeof DuoSessionsRoute
  '/erfahrungsberichte': typeof ErfahrungsberichteRoute
  '/faq': typeof FaqRoute
  '/fotoshooting': typeof FotoshootingRoute
  '/impressum': typeof ImpressumRoute
  '/kalender': typeof KalenderRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/mcp': typeof McpRoute
  '/newsletter-bestaetigen': typeof NewsletterBestaetigenRoute
  '/online': typeof OnlineRoute
  '/preise': typeof PreiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabus': typeof TabusRoute
  '/ueber-mich': typeof UeberMichRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal': typeof JournalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/agb': typeof AuthenticatedAdminAgbRoute
  '/admin/contentdreh': typeof AuthenticatedAdminContentdrehRoute
  '/admin/custom': typeof AuthenticatedAdminCustomRoute
  '/admin/duo': typeof AuthenticatedAdminDuoRoute
  '/admin/erfahrungsberichte': typeof AuthenticatedAdminErfahrungsberichteRoute
  '/admin/fotoshooting': typeof AuthenticatedAdminFotoshootingRoute
  '/admin/kalender': typeof AuthenticatedAdminKalenderRoute
  '/admin/kassenbuch': typeof AuthenticatedAdminKassenbuchRoute
  '/admin/kunden': typeof AuthenticatedAdminKundenRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/termine': typeof AuthenticatedAdminTermineRoute
  '/admin/terminplan': typeof AuthenticatedAdminTerminplanRoute
  '/admin/umplanen': typeof AuthenticatedAdminUmplanenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/buchung/$id': typeof AuthenticatedAdminBuchungIdRoute
  '/admin/email-vorschau/$logId': typeof AuthenticatedAdminEmailVorschauLogIdRoute
  '/api/public/calendar/$': typeof ApiPublicCalendarSplatRoute
  '/api/public/hooks/payment-reminders': typeof ApiPublicHooksPaymentRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/buchung': typeof BuchungRoute
  '/content-dreh': typeof ContentDrehRoute
  '/custom': typeof CustomRoute
  '/datenschutz': typeof DatenschutzRoute
  '/duo-sessions': typeof DuoSessionsRoute
  '/erfahrungsberichte': typeof ErfahrungsberichteRoute
  '/faq': typeof FaqRoute
  '/fotoshooting': typeof FotoshootingRoute
  '/impressum': typeof ImpressumRoute
  '/kalender': typeof KalenderRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/mcp': typeof McpRoute
  '/newsletter-bestaetigen': typeof NewsletterBestaetigenRoute
  '/online': typeof OnlineRoute
  '/preise': typeof PreiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabus': typeof TabusRoute
  '/ueber-mich': typeof UeberMichRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/agb': typeof AuthenticatedAdminAgbRoute
  '/_authenticated/admin/contentdreh': typeof AuthenticatedAdminContentdrehRoute
  '/_authenticated/admin/custom': typeof AuthenticatedAdminCustomRoute
  '/_authenticated/admin/duo': typeof AuthenticatedAdminDuoRoute
  '/_authenticated/admin/erfahrungsberichte': typeof AuthenticatedAdminErfahrungsberichteRoute
  '/_authenticated/admin/fotoshooting': typeof AuthenticatedAdminFotoshootingRoute
  '/_authenticated/admin/kalender': typeof AuthenticatedAdminKalenderRoute
  '/_authenticated/admin/kassenbuch': typeof AuthenticatedAdminKassenbuchRoute
  '/_authenticated/admin/kunden': typeof AuthenticatedAdminKundenRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/termine': typeof AuthenticatedAdminTermineRoute
  '/_authenticated/admin/terminplan': typeof AuthenticatedAdminTerminplanRoute
  '/_authenticated/admin/umplanen': typeof AuthenticatedAdminUmplanenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/buchung/$id': typeof AuthenticatedAdminBuchungIdRoute
  '/_authenticated/admin/email-vorschau/$logId': typeof AuthenticatedAdminEmailVorschauLogIdRoute
  '/api/public/calendar/$': typeof ApiPublicCalendarSplatRoute
  '/api/public/hooks/payment-reminders': typeof ApiPublicHooksPaymentRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/auth'
    | '/buchung'
    | '/content-dreh'
    | '/custom'
    | '/datenschutz'
    | '/duo-sessions'
    | '/erfahrungsberichte'
    | '/faq'
    | '/fotoshooting'
    | '/impressum'
    | '/kalender'
    | '/kontakt'
    | '/leistungen'
    | '/mcp'
    | '/newsletter-bestaetigen'
    | '/online'
    | '/preise'
    | '/sitemap.xml'
    | '/tabus'
    | '/ueber-mich'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/email/unsubscribe'
    | '/journal/$slug'
    | '/journal/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/agb'
    | '/admin/contentdreh'
    | '/admin/custom'
    | '/admin/duo'
    | '/admin/erfahrungsberichte'
    | '/admin/fotoshooting'
    | '/admin/kalender'
    | '/admin/kassenbuch'
    | '/admin/kunden'
    | '/admin/newsletter'
    | '/admin/termine'
    | '/admin/terminplan'
    | '/admin/umplanen'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/admin/buchung/$id'
    | '/admin/email-vorschau/$logId'
    | '/api/public/calendar/$'
    | '/api/public/hooks/payment-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/auth'
    | '/buchung'
    | '/content-dreh'
    | '/custom'
    | '/datenschutz'
    | '/duo-sessions'
    | '/erfahrungsberichte'
    | '/faq'
    | '/fotoshooting'
    | '/impressum'
    | '/kalender'
    | '/kontakt'
    | '/leistungen'
    | '/mcp'
    | '/newsletter-bestaetigen'
    | '/online'
    | '/preise'
    | '/sitemap.xml'
    | '/tabus'
    | '/ueber-mich'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/email/unsubscribe'
    | '/journal/$slug'
    | '/journal'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/agb'
    | '/admin/contentdreh'
    | '/admin/custom'
    | '/admin/duo'
    | '/admin/erfahrungsberichte'
    | '/admin/fotoshooting'
    | '/admin/kalender'
    | '/admin/kassenbuch'
    | '/admin/kunden'
    | '/admin/newsletter'
    | '/admin/termine'
    | '/admin/terminplan'
    | '/admin/umplanen'
    | '/lovable/email/suppression'
    | '/admin'
    | '/admin/buchung/$id'
    | '/admin/email-vorschau/$logId'
    | '/api/public/calendar/$'
    | '/api/public/hooks/payment-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agb'
    | '/auth'
    | '/buchung'
    | '/content-dreh'
    | '/custom'
    | '/datenschutz'
    | '/duo-sessions'
    | '/erfahrungsberichte'
    | '/faq'
    | '/fotoshooting'
    | '/impressum'
    | '/kalender'
    | '/kontakt'
    | '/leistungen'
    | '/mcp'
    | '/newsletter-bestaetigen'
    | '/online'
    | '/preise'
    | '/sitemap.xml'
    | '/tabus'
    | '/ueber-mich'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/email/unsubscribe'
    | '/journal/$slug'
    | '/journal/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/agb'
    | '/_authenticated/admin/contentdreh'
    | '/_authenticated/admin/custom'
    | '/_authenticated/admin/duo'
    | '/_authenticated/admin/erfahrungsberichte'
    | '/_authenticated/admin/fotoshooting'
    | '/_authenticated/admin/kalender'
    | '/_authenticated/admin/kassenbuch'
    | '/_authenticated/admin/kunden'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/termine'
    | '/_authenticated/admin/terminplan'
    | '/_authenticated/admin/umplanen'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/buchung/$id'
    | '/_authenticated/admin/email-vorschau/$logId'
    | '/api/public/calendar/$'
    | '/api/public/hooks/payment-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgbRoute: typeof AgbRoute
  AuthRoute: typeof AuthRoute
  BuchungRoute: typeof BuchungRoute
  ContentDrehRoute: typeof ContentDrehRoute
  CustomRoute: typeof CustomRoute
  DatenschutzRoute: typeof DatenschutzRoute
  DuoSessionsRoute: typeof DuoSessionsRoute
  ErfahrungsberichteRoute: typeof ErfahrungsberichteRoute
  FaqRoute: typeof FaqRoute
  FotoshootingRoute: typeof FotoshootingRoute
  ImpressumRoute: typeof ImpressumRoute
  KalenderRoute: typeof KalenderRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  McpRoute: typeof McpRoute
  NewsletterBestaetigenRoute: typeof NewsletterBestaetigenRoute
  OnlineRoute: typeof OnlineRoute
  PreiseRoute: typeof PreiseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TabusRoute: typeof TabusRoute
  UeberMichRoute: typeof UeberMichRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCalendarSplatRoute: typeof ApiPublicCalendarSplatRoute
  ApiPublicHooksPaymentRemindersRoute: typeof ApiPublicHooksPaymentRemindersRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabus': {
      id: '/tabus'
      path: '/tabus'
      fullPath: '/tabus'
      preLoaderRoute: typeof TabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter-bestaetigen': {
      id: '/newsletter-bestaetigen'
      path: '/newsletter-bestaetigen'
      fullPath: '/newsletter-bestaetigen'
      preLoaderRoute: typeof NewsletterBestaetigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotoshooting': {
      id: '/fotoshooting'
      path: '/fotoshooting'
      fullPath: '/fotoshooting'
      preLoaderRoute: typeof FotoshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfahrungsberichte': {
      id: '/erfahrungsberichte'
      path: '/erfahrungsberichte'
      fullPath: '/erfahrungsberichte'
      preLoaderRoute: typeof ErfahrungsberichteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duo-sessions': {
      id: '/duo-sessions'
      path: '/duo-sessions'
      fullPath: '/duo-sessions'
      preLoaderRoute: typeof DuoSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-dreh': {
      id: '/content-dreh'
      path: '/content-dreh'
      fullPath: '/content-dreh'
      preLoaderRoute: typeof ContentDrehRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchung': {
      id: '/buchung'
      path: '/buchung'
      fullPath: '/buchung'
      preLoaderRoute: typeof BuchungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/umplanen': {
      id: '/_authenticated/admin/umplanen'
      path: '/umplanen'
      fullPath: '/admin/umplanen'
      preLoaderRoute: typeof AuthenticatedAdminUmplanenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/terminplan': {
      id: '/_authenticated/admin/terminplan'
      path: '/terminplan'
      fullPath: '/admin/terminplan'
      preLoaderRoute: typeof AuthenticatedAdminTerminplanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/termine': {
      id: '/_authenticated/admin/termine'
      path: '/termine'
      fullPath: '/admin/termine'
      preLoaderRoute: typeof AuthenticatedAdminTermineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kunden': {
      id: '/_authenticated/admin/kunden'
      path: '/kunden'
      fullPath: '/admin/kunden'
      preLoaderRoute: typeof AuthenticatedAdminKundenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kassenbuch': {
      id: '/_authenticated/admin/kassenbuch'
      path: '/kassenbuch'
      fullPath: '/admin/kassenbuch'
      preLoaderRoute: typeof AuthenticatedAdminKassenbuchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kalender': {
      id: '/_authenticated/admin/kalender'
      path: '/kalender'
      fullPath: '/admin/kalender'
      preLoaderRoute: typeof AuthenticatedAdminKalenderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fotoshooting': {
      id: '/_authenticated/admin/fotoshooting'
      path: '/fotoshooting'
      fullPath: '/admin/fotoshooting'
      preLoaderRoute: typeof AuthenticatedAdminFotoshootingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/erfahrungsberichte': {
      id: '/_authenticated/admin/erfahrungsberichte'
      path: '/erfahrungsberichte'
      fullPath: '/admin/erfahrungsberichte'
      preLoaderRoute: typeof AuthenticatedAdminErfahrungsberichteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/duo': {
      id: '/_authenticated/admin/duo'
      path: '/duo'
      fullPath: '/admin/duo'
      preLoaderRoute: typeof AuthenticatedAdminDuoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/custom': {
      id: '/_authenticated/admin/custom'
      path: '/custom'
      fullPath: '/admin/custom'
      preLoaderRoute: typeof AuthenticatedAdminCustomRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contentdreh': {
      id: '/_authenticated/admin/contentdreh'
      path: '/contentdreh'
      fullPath: '/admin/contentdreh'
      preLoaderRoute: typeof AuthenticatedAdminContentdrehRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agb': {
      id: '/_authenticated/admin/agb'
      path: '/agb'
      fullPath: '/admin/agb'
      preLoaderRoute: typeof AuthenticatedAdminAgbRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/payment-reminders': {
      id: '/api/public/hooks/payment-reminders'
      path: '/api/public/hooks/payment-reminders'
      fullPath: '/api/public/hooks/payment-reminders'
      preLoaderRoute: typeof ApiPublicHooksPaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$': {
      id: '/api/public/calendar/$'
      path: '/api/public/calendar/$'
      fullPath: '/api/public/calendar/$'
      preLoaderRoute: typeof ApiPublicCalendarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/email-vorschau/$logId': {
      id: '/_authenticated/admin/email-vorschau/$logId'
      path: '/email-vorschau/$logId'
      fullPath: '/admin/email-vorschau/$logId'
      preLoaderRoute: typeof AuthenticatedAdminEmailVorschauLogIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buchung/$id': {
      id: '/_authenticated/admin/buchung/$id'
      path: '/buchung/$id'
      fullPath: '/admin/buchung/$id'
      preLoaderRoute: typeof AuthenticatedAdminBuchungIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgbRoute: typeof AuthenticatedAdminAgbRoute
  AuthenticatedAdminContentdrehRoute: typeof AuthenticatedAdminContentdrehRoute
  AuthenticatedAdminCustomRoute: typeof AuthenticatedAdminCustomRoute
  AuthenticatedAdminDuoRoute: typeof AuthenticatedAdminDuoRoute
  AuthenticatedAdminErfahrungsberichteRoute: typeof AuthenticatedAdminErfahrungsberichteRoute
  AuthenticatedAdminFotoshootingRoute: typeof AuthenticatedAdminFotoshootingRoute
  AuthenticatedAdminKalenderRoute: typeof AuthenticatedAdminKalenderRoute
  AuthenticatedAdminKassenbuchRoute: typeof AuthenticatedAdminKassenbuchRoute
  AuthenticatedAdminKundenRoute: typeof AuthenticatedAdminKundenRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminTermineRoute: typeof AuthenticatedAdminTermineRoute
  AuthenticatedAdminTerminplanRoute: typeof AuthenticatedAdminTerminplanRoute
  AuthenticatedAdminUmplanenRoute: typeof AuthenticatedAdminUmplanenRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBuchungIdRoute: typeof AuthenticatedAdminBuchungIdRoute
  AuthenticatedAdminEmailVorschauLogIdRoute: typeof AuthenticatedAdminEmailVorschauLogIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgbRoute: AuthenticatedAdminAgbRoute,
  AuthenticatedAdminContentdrehRoute: AuthenticatedAdminContentdrehRoute,
  AuthenticatedAdminCustomRoute: AuthenticatedAdminCustomRoute,
  AuthenticatedAdminDuoRoute: AuthenticatedAdminDuoRoute,
  AuthenticatedAdminErfahrungsberichteRoute:
    AuthenticatedAdminErfahrungsberichteRoute,
  AuthenticatedAdminFotoshootingRoute: AuthenticatedAdminFotoshootingRoute,
  AuthenticatedAdminKalenderRoute: AuthenticatedAdminKalenderRoute,
  AuthenticatedAdminKassenbuchRoute: AuthenticatedAdminKassenbuchRoute,
  AuthenticatedAdminKundenRoute: AuthenticatedAdminKundenRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminTermineRoute: AuthenticatedAdminTermineRoute,
  AuthenticatedAdminTerminplanRoute: AuthenticatedAdminTerminplanRoute,
  AuthenticatedAdminUmplanenRoute: AuthenticatedAdminUmplanenRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBuchungIdRoute: AuthenticatedAdminBuchungIdRoute,
  AuthenticatedAdminEmailVorschauLogIdRoute:
    AuthenticatedAdminEmailVorschauLogIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgbRoute: AgbRoute,
  AuthRoute: AuthRoute,
  BuchungRoute: BuchungRoute,
  ContentDrehRoute: ContentDrehRoute,
  CustomRoute: CustomRoute,
  DatenschutzRoute: DatenschutzRoute,
  DuoSessionsRoute: DuoSessionsRoute,
  ErfahrungsberichteRoute: ErfahrungsberichteRoute,
  FaqRoute: FaqRoute,
  FotoshootingRoute: FotoshootingRoute,
  ImpressumRoute: ImpressumRoute,
  KalenderRoute: KalenderRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  McpRoute: McpRoute,
  NewsletterBestaetigenRoute: NewsletterBestaetigenRoute,
  OnlineRoute: OnlineRoute,
  PreiseRoute: PreiseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TabusRoute: TabusRoute,
  UeberMichRoute: UeberMichRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCalendarSplatRoute: ApiPublicCalendarSplatRoute,
  ApiPublicHooksPaymentRemindersRoute: ApiPublicHooksPaymentRemindersRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
